// <auto-generated />
using Library.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260926193615_InitialCatalog")]
    partial class InitialCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Library.Domain.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Authors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ana Torres"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Carlos Méndez"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Laura Ramírez"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Diego Vargas"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sofía Herrera"
                        });
                });

            modelBuilder.Entity("Library.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Isbn")
                        .IsUnique();

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 1,
                            Isbn = "9780000000019",
                            PublicationYear = 2018,
                            Title = "Arquitectura de software"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CategoryId = 1,
                            Isbn = "9780000000026",
                            PublicationYear = 2016,
                            Title = "Fundamentos de bases de datos"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CategoryId = 1,
                            Isbn = "9780000000033",
                            PublicationYear = 2020,
                            Title = "Redes distribuidas"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            CategoryId = 1,
                            Isbn = "9780000000040",
                            PublicationYear = 2014,
                            Title = "Patrones de diseño"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            CategoryId = 2,
                            Isbn = "9780000000057",
                            PublicationYear = 2012,
                            Title = "Historia de la ciencia"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 1,
                            CategoryId = 2,
                            Isbn = "9780000000064",
                            PublicationYear = 2019,
                            Title = "Álgebra lineal aplicada"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 2,
                            CategoryId = 2,
                            Isbn = "9780000000071",
                            PublicationYear = 2017,
                            Title = "Cálculo para ingeniería"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 3,
                            CategoryId = 3,
                            Isbn = "9780000000088",
                            PublicationYear = 2015,
                            Title = "Literatura latinoamericana"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 4,
                            CategoryId = 3,
                            Isbn = "9780000000095",
                            PublicationYear = 2021,
                            Title = "Narrativas contemporáneas"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 5,
                            CategoryId = 3,
                            Isbn = "9780000000101",
                            PublicationYear = 2013,
                            Title = "Poesía y memoria"
                        });
                });

            modelBuilder.Entity("Library.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tecnología"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ciencias"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Literatura"
                        });
                });

            modelBuilder.Entity("Library.Domain.Entities.Book", b =>
                {
                    b.HasOne("Library.Domain.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Library.Domain.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Library.Domain.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Library.Domain.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
